import SyncModeController from "./sync_mode_controller.coffee";
application.register("sync-mode", SyncModeController);
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ApplicationController from "./application_controller";
application.register("application", ApplicationController);

import ConsentController from "./consent_controller";
application.register("consent", ConsentController);

import CtaParticlesController from "./cta_particles_controller";
application.register("cta-particles", CtaParticlesController);

import DismissibleController from "./dismissible_controller";
application.register("dismissible", DismissibleController);

import DocsifyController from "./docsify_controller";
application.register("docsify", DocsifyController);

import EnhancedApplicationController from "./enhanced_application_controller";
application.register("enhanced-application", EnhancedApplicationController);

import ExperienceUploadController from "./experience_upload_controller";
application.register("experience-upload", ExperienceUploadController);

import FormAutoSubmitController from "./form_auto_submit_controller";
application.register("form-auto-submit", FormAutoSubmitController);

import FoundationController from "./foundation_controller";
application.register("foundation", FoundationController);

import HyperspaceController from "./hyperspace_controller";
application.register("hyperspace", HyperspaceController);

import InstanceSettingsController from "./instance_settings_controller";
application.register("instance-settings", InstanceSettingsController);

import LanguagePickerController from "./language_picker_controller";
application.register("language-picker", LanguagePickerController);

import LinkController from "./link_controller";
application.register("link", LinkController);

import LocomotiveScrollController from "./locomotive_scroll_controller";
application.register("locomotive-scroll", LocomotiveScrollController);

import NavigationShortcutsController from "./navigation_shortcuts_controller";
application.register("navigation-shortcuts", NavigationShortcutsController);

import OffCanvasController from "./off_canvas_controller";
application.register("off-canvas", OffCanvasController);

import ParallaxBackgroundController from "./parallax_background_controller";
application.register("parallax-background", ParallaxBackgroundController);

import RaindropController from "./raindrop_controller";
application.register("raindrop", RaindropController);

import SearchController from "./search_controller";
application.register("search", SearchController);

import SearchUrlUpdaterController from "./search_url_updater_controller";
application.register("search-url-updater", SearchUrlUpdaterController);

import SidebarPopoverController from "./sidebar_popover_controller";
application.register("sidebar-popover", SidebarPopoverController);

import ToastController from "./toast_controller";
application.register("toast", ToastController);

import WebsocketP2pController from "./websocket_p2p_controller";
application.register("websocket-p2p", WebsocketP2pController);

import MetaverseMapController from "./metaverse_map_controller.coffee";
application.register("metaverse-map", MetaverseMapController);

import MetaversePanelSwitchController from "./metaverse_panel_switch_controller.coffee";
application.register("metaverse-panel-switch", MetaversePanelSwitchController);
