# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.3.7", "< 3.4"

# Security: Enforce 1-week minimum age for all gems
# Install with: bundle plugin install bundler-age_gate --path plugins/bundler-age_gate
plugin "bundler-age_gate", path: "plugins/bundler-age_gate"

gem "active_hashcash"
gem "activerecord-enhancedsqlite3-adapter"
gem "active_storage_db", ">= 1.5.0"
gem "active_storage_validations", ">= 3.0.3"
gem "argon2"
gem "aws-sdk-core", "3.252.0"
gem "aws-sdk-s3", "1.225.1"
gem "aws-partitions", "1.1255.0"
gem "audits1984"
gem "better_html"
gem "bootsnap", require: false
gem "cancancan"
gem "capybara"
gem "chunky_png"
gem "comfortable_media_surfer", ">= 3.1.5"
gem "connection_pool", "< 3.0"
gem "console1984", ">= 0.2.3"
gem "counter_culture", "~> 3.13", ">= 3.13.2"
gem "fast_blank"
gem "fast_underscore"
gem "federails", ">= 0.8.0"
gem "federails-moderation", ">= 0.4.0"
gem "fiddle"
gem "freezolite"
gem "friendly_id", ">= 5.6.0"
gem "gemoji"
gem "goldiloader"
gem "google_robotstxt_parser", path: "vendor/gems/google_robotstxt_parser"
gem "graphql_rails"
gem "grpc"
gem "haml", "~> 5.2"
gem "haml-rails", ">= 3.0.0"
gem "httparty"
gem "image_processing"
gem "inky-rb", require: "inky"
gem "invisible_captcha"
gem "jbuilder", ">= 2.15.0"
gem "kaminari-i18n"
gem "lockbox"
gem "memo_wise"
gem "minify_html", "0.16.4"
gem "nokogiri"
gem "oj", "= 3.17.3"
gem "omniauth_openid_connect"
gem "ostruct"
gem "p2p_streams_channel"
gem "passenger", ">= 6.0.20", require: "phusion_passenger/rack_handler"
gem "permessage_deflate"
gem "pluck_in_batches"
gem "premailer-rails"
gem "propshaft", ">= 1.3.2"
gem "rack-attack"
gem "rack-brotli"
gem "rack-cors"
gem "rack-mini-profiler"
gem "rails", ">= 8.0.5"
gem "rails-controller-testing"
gem "rails-i18n", ">= 8.1.0"
gem "re2"
gem "reactionview", ">= 0.1.3"
gem "react_on_rails", "16.1.0"
gem "reform"
gem "rodauth-guest"
gem "rodauth-i18n", ">= 0.9.0"
gem "rodauth-model"
gem "rodauth-oauth"
gem "rodauth-omniauth"
gem "rodauth-pwned"
gem "rodauth-rails", ">= 2.1.1"
gem "rolify"
gem "rspec"
gem "rubyzip"
gem "second_level_cache", "~> 2.7", path: "vendor/gems/second_level_cache"
gem "selenium-webdriver"
gem "sentry-rails", ">= 5.28.1"
gem "sentry-ruby", ">= 5.28.1"
gem "sequel-activerecord_connection", ">= 2.0.1"
gem "shakapacker", ">= 9.6.0"
gem "sitemap_generator"
gem "snappy"
gem "solid_cable", ">= 4.0.0"
gem "solid_cache", ">= 1.0.8"
gem "solid_queue", ">= 1.2.2"
gem "sqlite3"
gem "stimulus-rails"
gem "stimulus_reflex", "3.5.4"
gem "sys-filesystem"
gem "thor", ">= 1.4.0"
gem "thredded", "~> 1.2"
gem "thredded-markdown_coderay"
gem "thredded-markdown_katex"
gem "tilt"
gem "trailblazer"
gem "trilogy"
gem "turbo_power"
gem "turbo-rails", ">= 2.0.19"
gem "tzinfo-data", ">= 1.2025.3"
gem "unicode"
gem "unidecoder"
gem "view_component", ">= 4.9.0"
gem "vite_rails", ">= 3.0.20"
gem "voight_kampff"
gem "worker_killer"
gem "y-rb_actioncable"
gem "zip_kit"
gem "zstd-ruby"

group :development, :test do
  gem "debug"
  gem "dotenv-rails", ">= 3.2.0"
  gem "listen"
  gem "parallel_tests"
  gem "spring-commands-parallel-tests"
  gem "spring-commands-rubocop"
end

group :development do
  gem "brakeman"
  gem "erb-formatter"
  gem "erb_lint"
  gem "fasterer"
  gem "flamegraph"
  gem "grpc-tools"
  gem "haml-lint"
  gem "i18n-tasks", ">= 1.1.0"
  gem "overmind"
  gem "redis"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails", ">= 2.34.0"
  gem "spring"
  gem "stackprof"
  gem "web-console", ">= 4.3.0"
end

group :test do
  gem "mocha"
  gem "mysql2"
end

gem "rails_http_preload", "~> 0.3.0"
